### ISSUE TITLE
mapfile.py fails when COMMON region is in map file (IDFGH-11738)

### ISSUE THREAD

**Issue by johndrewery** [espressif/esp-idf-size#1]
An ESP32-S3 application compiles and links correctly and produced a map.  This map has COMMON data 'phy_version_str' and 'chip7_phy_init_ctrl'.  A section of the map file is shown below.  Note that the COMMON data creates offsets, incrementing the address from 0x3fcb6a78 to 0x3fcb6aa0 and then to 0x3fcb6acc for the objects of size 0x28 and 0x2a.  However as can be seen in mapfile.py these COMMON areas are not accounted for. 

This leads to a fault in _validate_sections where symbol .bss.ble_hs_id_rnd is expected at 0x3fcb6a7a (= 0x3fcb6a78 + fill of 2) but in fact the symbol is at 0x3fcb6acc.

This causes the error 'error:  input section .bss.ble_hs_id_rnd is not at expected address 0x3fcb6a7a'

Map file extract:

 .bss           0x3fcb6938        0x4 /Users/johndrewery/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/lib/esp32s3/no-rtti/libc.a(libc_a-environ.o)
 .bss           0x3fcb693c      0x13c /Users/johndrewery/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/lib/esp32s3/no-rtti/libc.a(libc_a-findfp.o)
                0x3fcb693c                __sf
                0x3fcb6a74                __stdio_exit_handler
 *(.dynbss .dynsbss .gnu.linkonce.b .gnu.linkonce.b.* .gnu.linkonce.sb .gnu.linkonce.sb.* .gnu.linkonce.sb2 .gnu.linkonce.sb2.* .sbss .sbss.* .sbss2 .sbss2.* .scommon .share.mem)
 *(.ext_ram.bss .ext_ram.bss.*)
 *(EXCLUDE_FILE(*libnimble.a *libbtdm_app.a *libbt.a *libble_app.a) COMMON)
 COMMON         0x3fcb6a78       0x28 /Users/johndrewery/esp/esp-idf/components/esp_phy/lib/esp32s3/libphy.a(phy_debug.o)
                0x3fcb6a78                phy_version_str
 COMMON         0x3fcb6aa0       0x2a /Users/johndrewery/esp/esp-idf/components/esp_phy/lib/esp32s3/libphy.a(phy_init.o)
                0x3fcb6aa0                chip7_phy_init_ctrl
                0x3fcb6acc                        . = ALIGN (0x4)
 *fill*         0x3fcb6aca        0x2 
                0x3fcb6acc                        _bt_controller_bss_start = ABSOLUTE (.)
 *libble_app.a:(.bss .bss.*)
                0x3fcb6acc                        . = ALIGN (0x4)
                0x3fcb6acc                        _bt_controller_bss_end = ABSOLUTE (.)
                0x3fcb6acc                        . = ALIGN (0x4)
                0x3fcb6acc                        _bt_controller_common_start = ABSOLUTE (.)
 *libble_app.a:(COMMON)
                0x3fcb6acc                        . = ALIGN (0x4)
                0x3fcb6acc                        _bt_controller_common_end = ABSOLUTE (.)
                0x3fcb6acc                        . = ALIGN (0x4)
                0x3fcb6acc                        _bt_bss_start = ABSOLUTE (.)
 *libbt.a:(.bss .bss.*)
 .bss.ble_hs_id_rnd
                0x3fcb6acc        0x6 esp-idf/bt/libbt.a(ble_hs_id.c.obj)

**Comment by fhrbata** [comment]
Hello @johndrewery ,

thank you very much for this report and for trying the ng version. Yes, there seems to be some bug in the parser. I can reproduce similar behavior with e.g. `examples/bluetooth/blufi`. The original parser can handle this. I will take a look.

Thank you!
