### ISSUE TITLE
Sorting options other than by total size (IDFGH-12428)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf-size#3]
Title.
At the very least, an option to sort the text (table) by IRAM is a necessity.
If possible, the ability to do multi-key sorting of the table, csv and tree formats would be really great for deeper analysis of the binary composition.

**Comment by fhrbata** [comment]
Hello @KaeLL ,

thank you very much for the suggestion. Do you think that something like [sort -k](https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html) behavior would be sufficient for table and csv format. Meaning there would be another command line option specifying by which column the table should be sorted. So e.g. `idf.py size-components -c 2` would sort the table based on column `2`. The names and output sections may differ on different targets, so this approach should be more generic.  The tree sorting could be probably done based on levels.  What do you think?

Thank you

**Comment by KaeLL** [comment]
Why isn't lexicographical sorting of .a(rchives) names supported (sorting of column 0)? I'd like to separate IDF's components from my projects' components, which can be easily done by sorting column 0 of a project which components' names have a common prefix, like mine do. By itself, that may not be reason enough, given that it's a me problem, but there's also the argument of consistency, as there's no reason why the archive names shouldn't be a valid criteria.

**Comment by fhrbata** [comment]
Hello @KaeLL,

Thank you for your feedback. The primary reason is likely that the archive names, or any row names in the archives/files/archive_details tables, do not include the diff value, which can also be used as a sorting value when the `--sort-diff` option is applied. I understand your point that this might seem inconsistent. Could you please file a new ticket for this issue? I will look into it.

Thank you very much.
