### ISSUE TITLE
Sort idf_size table by components (IDFGH-12864)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf-size#4]
Follow up from #3
Sorting by column 0, the archive files' names, is currently not supported, but it would be interesting to add that because it may allow filtering of user components from IDF components and for consistency's sake.

**Comment by fhrbata** [comment]
Hello @KaeLL ,

@KaeLL, thanks for following up and reporting this issue! I'll investigate it. Just thinking out loud here, would it make sens    e to have something like a `--filter` option that accepts regex and prints only the matching archives?

Thank you

**Comment by KaeLL** [comment]
Even better, since I'm assuming it'd be possible to combine it with the sorting option to filter and then sort the output.

**Comment by fhrbata** [comment]
> Even better, since I'm assuming it'd be possible to combine it with the sorting option to filter and then sort the output.

Yes, that's my initial thought. I'll work on preparing something and likely share the interface results here for further discussi    on. Thank you.

**Comment by KaeLL** [comment]
Perfect. Thank you!

**Comment by fhrbata** [comment]
Following an internal discussion, I switched the approach from using regex to wildcards, as they should be easier to use and flexible enough for this simple filtering. Thank you for your suggestions and help. I hope you find it useful.
